# Generated by Django 4.0.4 on 2022-11-04 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcmapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hash_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kcmapp.cashbook')),
            ],
        ),
    ]
