# Generated by Django 4.0.4 on 2022-11-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcmapp', '0003_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='kcmapp.hashtag'),
        ),
    ]
